title = "Matt Potok"
baseurl = "http://mattpotok.com/"
languageCode = "en-us"
theme = "ocean-night"
publishDir = "docs"

[author]
    name = "Matt Potok"

[params]
    description = "Personal website"
    
    facebook = "https://www.facebook.com/matt.potok.5"
    github = "https://github.com/mattpotok"
    linkedin = "https://www.linkedin.com/in/matthew-potok/"
    youtube = "https://www.youtube.com/mattpotok"
